apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y20144p73-go 
  janus-idp.io/tekton: y20144p73-go
  backstage.io/kubernetes-id: y20144p73-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y20144p73-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  